### ISSUE TITLE
Try loading config from ~/.config

### ISSUE THREAD

**Issue by xtexx** [haxwithaxe/ntfyr#2]
Maybe we could attempt to read default config from `~/.config` or `$XDG_CONFIG_HOME` ?

**Comment by haxwithaxe** [comment]
It should be doing that in the latest version. Is that not working for you?

**Comment by xtexx** [comment]
```
xtex@xtex ~ (main)> XDG_CONFIG_HOME=$(pwd) ntfyr -t test -m test --log-level DEBUG
WARNING:ntfyr: The config source "/etc/ntfyr/config.ini" does not exist.
WARNING:ntfyr: The config source "/usr/local/etc/ntfyr/config.ini" does not exist.
WARNING:ntfyr: Failed to read config source /home/xtex: IsADirectoryError: [Errno 21] Is a directory: '/home/xtex'
```
It is regarding `$XDG_CONFIG_HOME` as a file path rather than a directory.

**Comment by haxwithaxe** [comment]
Ah, okay. It's supposed to be adding ``ntfyr/config.ini`` to `$XDG_CONFIG_HOME` which it currently is not. I should have a fix available in the next couple days.

**Comment by haxwithaxe** [comment]
The fix is in the main branch if you want to grab it directly from git. I don't have time to roll and verify a release at the moment but I hope to be able to do that tonight.
